//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test8
{
    using System;
    using System.Collections.Generic;
    
    public partial class stu
    {
        public int id { get; set; }
        public string passw { get; set; }
        public string namee { get; set; }
        public Nullable<int> age { get; set; }
        public string addrese { get; set; }
        public string teacher { get; set; }
        public string grade { get; set; }
    }
}
